---
abstract: 'An implementation of the EPP XML language'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
build_requires:
  Scriptalicious: 0
  XML::Compare: 0.03
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-EPP
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.54
  MooseX::Timestamp: 0
  PRANG: 0.1
  perl: 5.01
version: 0.04
