---
abstract: 'An implementation of the EPP XML language'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Scriptalicious: 0
  XML::Compare: 0.02
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-EPP
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.54
  PRANG: 0.07
  perl: 5.010001
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.02
