=head1 NAME

? - implement ?

=head1 SYNOPSIS

TODO

=head1 DESCRIPTION

...

=head2 XML Schema Definition

 <complexType name="chkDataType">
  <sequence>
    <element name="cd" type="domain:checkType"
     maxOccurs="unbounded"/>
  </sequence>
 </complexType>

=head2 Attributes

There are no xml attributes on this element.

=head2 Elements

=over

=item B<items>

This element is of type 'ArrayRef[XML::EPP::Domain::Check::Status]' and is not required.  It corresponds to the XML element of name 'cd'.

=back

=head1 SEE ALSO

ToMake

=head1 AUTHOR AND LICENSE

Development commissioned by NZ Registry Services, and carried out by
Catalyst IT - L<http://www.catalyst.net.nz/>

Copyright 2009, 2010, NZ Registry Services.  This module is licensed
under the Artistic License v2.0, which permits relicensing under other
Free Software licenses.

=cut

