=head1 NAME

? - implement ?

=head1 SYNOPSIS

TODO

=head1 DESCRIPTION

...

=head2 XML Schema Definition

 <complexType name="postalInfoType">
   <sequence>
     <element name="name" type="contact:postalLineType"/>
     <element name="org" type="contact:optPostalLineType"
      minOccurs="0"/>
     <element name="addr" type="contact:addrType"/>
   </sequence>
   <attribute name="type" type="contact:postalInfoEnumType"
    use="required"/>
 </complexType>

=head2 Attributes

=over

=item B<type>

This attribute is of type 'XML::EPP::Contact::postalInfoEnumType' and is not required.

=back

=head2 Elements

=over

=item B<org>

This element is of type 'XML::EPP::Contact::optPostalLineType' and is not required.

=item B<name>

This element is of type 'XML::EPP::Contact::postalLineType' and is not required.

=item B<addr>

This element is of type 'XML::EPP::Contact::Addr' and is not required.

=back

=head1 SEE ALSO

ToMake

=head1 AUTHOR AND LICENSE

Development commissioned by NZ Registry Services, and carried out by
Catalyst IT - L<http://www.catalyst.net.nz/>

Copyright 2009, 2010, NZ Registry Services.  This module is licensed
under the Artistic License v2.0, which permits relicensing under other
Free Software licenses.

=cut

