=head1 NAME

XML::EPP::Plugin

=head1 SYNOPSIS

 package XML::EPP::Domain;
 use Moose::Role;
 with qw(XML::EPP::Plugin PRANG::Graph);
 sub is_command { 0|1 };
 1;

=head1 DESCRIPTION

Provides a role which can be incorporated to show that this element is a plugin.

=head2 XML Schema Definition

n/a

=head2 Attributes

Failed to find any attributes on this element.

=head2 Elements

Failed to find any child elements on this element.

=head1 SEE ALSO

ToMake

=head1 AUTHOR AND LICENSE

Development commissioned by NZ Registry Services, and carried out by
Catalyst IT - L<http://www.catalyst.net.nz/>

Copyright 2009, 2010, NZ Registry Services.  This module is licensed
under the Artistic License v2.0, which permits relicensing under other
Free Software licenses.

=cut

